### ISSUE TITLE
More (julia) packages to interface with

### ISSUE THREAD

**Issue by tlienart** [JuliaAI/MLJ#34]
This is a list to keep track of packages that should be considered in the near future with some notion of priority; feel free to comment with packages that should be considered or shotgunning an interface you'd be happy to help with.

### higher priority
- [x] Complete interface with [DecisionTree.jl](https://github.com/bensadeghi/DecisionTree.jl) e.g. categorical features part
- [ ] [Impute.jl](https://github.com/invenia/Impute.jl)
- [x] [Soss.jl](https://github.com/cscherrer/Soss.jl) at least for basic bayesian models such as bayesian regression or bayesian logreg --> this is happening on branch `soss`
- [x] Finish the interface with Multivariate Stats (e.g. subspace LDA is missing)
- [ ]  Complete the interface to Clustering.jl

### other models

- [ ]  [LowRankModels.jl](https://github.com/madeleineudell/LowRankModels.jl) and also [this mlj issue](https://github.com/alan-turing-institute/MLJ.jl/issues/44)
- [ ]  [ManifoldLearning.jl](https://github.com/wildart/ManifoldLearning.jl) also [this mlj issue](https://github.com/alan-turing-institute/MLJ.jl/issues/161)
- [x] [EvoTrees.jl](https://github.com/Evovest/EvoTrees.jl) and [this mlj issue](https://github.com/alan-turing-institute/MLJ.jl/issues/122)~~
- [ ] [tsne](https://github.com/lejon/TSne.jl)
- [ ] [umap](https://github.com/dillondaudert/UMAP.jl)
- [ ]  [NearestNeighborDescent](https://github.com/dillondaudert/NearestNeighborDescent.jl) 

---

- [ ] https://github.com/JuliaStats/StatsKit.jl 

- [ ] https://github.com/Marco-Congedo/PosDefManifoldML.jl **note**: objects are matrices, could maybe  use the images formalism.
